@startuml

actor user
participant client
participant server
participant CA

client -> CA : 操作系统or客户端预先安装CA
==https建立流程==
client -> server: 本地支持的加密算法列表以及SSL或者TLS版本
server -> server: 选出非对称加密算法f, 生成密钥对(k1, k2)
server -> client: 返回证书，以及公钥 k1
client -> client: 校验证书合法性，生成对称密钥k
client -> server: 用公钥k1加密k，生成加密包 k1(k)
server -> server: 使用私钥解析k1(k), k2(k1(k)) = k, 获取到密钥 k
==通信==
server -> client: 使用 k 对数据加密，k(data)
client -> client: 使用 k 对数据进行解密，k(k(data))
@enduml